/* Function Declaration */
double deg2rad(double);
double rad2deg(double);
double find_angle(double, double, double, double, double, double);
double find_distance(double, double, double, double, char);
double find_area(double, double, double, double, double, double);
double distanceBWTwoPoints(double, double, double, double);
void pointOfDivisionOFALineJoining(double, double, double, double, double, double);
void midPointOFTheLineJoining(double, double, double, double);
double areaOfTriangle(double, double, double, double, double, double);
double distanceBWTwoPointsInPolarCoordinate(double, double, double, double);
void cartesianToPolar(double, double);
void polarToCartesian(double, double);
double findCirlceDiameter(double);
double findCircleRadius(double);
double findCirlceArea(double);
int whichShapedOfConicSection(double, double, double, double, double, double);
void findCoordinateFocusEquationDirectixLengthLatusRectumOfParaBola(double);
double slopeOfALineThroughTwoPoints(double, double, double, double);
double slopOfStraightLine(double, double, double);
double slopeOfLineInclinationOfTheta(double);
double angleBWTwoLinesHavingSlopes(double, double);